[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[functions."replicate"]
  timeout = 300

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
